name: Build EasyCHD for release

on:
  push:
    branches: ["github-action-testing"]
    
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['macos-latest', 'macos-15-intel']

    steps:
    - uses: actions/checkout@v5
    - name: Setup Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pillow
        pip install -r requirements.txt

    - name: Build with Pyinstaller on ${{ matrix.os }}
      if: matrix.os == 'macos-latest'
      run: |
        pyinstaller --onefile --target-arch=arm64 -n=easyCHD -i=icon.png src/app.py

    - name: Build with Pyinstaller on ${{ matrix.os }}
      if: matrix.os == 'macos-15-intel'
      run: |
        pyinstaller --onefile -n=easyCHD -i=icon.png src/app.py